# See https://pre-commit.com for more information

fail_fast: true
default_install_hook_types: [commit-msg, pre-commit, pre-push]

repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: "v2.7.2"
    hooks:
      - id: conventional-commits
        args: ["-c", ".git-commits.yaml"]
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        stages: ["pre-commit"]
      - id: check-merge-conflict
        stages: ["pre-commit"]
      - id: check-added-large-files
        stages: ["pre-commit"]
        args: ["--maxkb=5000"]
      - id: check-ast
        stages: ["pre-commit"]
      - id: check-executables-have-shebangs
        stages: ["pre-commit"]
      - id: check-symlinks
        stages: ["pre-commit"]
      - id: check-toml
        stages: ["pre-commit"]
      - id: check-yaml
        stages: ["pre-commit"]
      - id: debug-statements
        stages: ["pre-commit"]
      - id: end-of-file-fixer
        stages: ["pre-commit"]
        exclude: |
          (?x)^(
              _pb2\.py|
              _pb2_grpc\.py
          )
      - id: trailing-whitespace
        stages: ["pre-commit"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.2
    hooks:
      - id: uv-lock
        args: ["--check"]
        stages: ["pre-commit"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.0"
    hooks:
      # Run the linter.
      - id: ruff-check
        name: ruff check
        stages: ["pre-commit"]
      # Run the formatter.
      - id: ruff-format
        name: ruff format
        stages: ["pre-commit"]

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.52.0 # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        name: pyrefly check
        pass_filenames: false # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        language: system # Use system-installed pyrefly
        stages: ["pre-commit"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest tests
        language: system
        pass_filenames: false
        files: \.py$
        stages: ["pre-push"]
# See https://pre-commit.com/hooks.html for more hooks
