# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true
default_install_hook_types: [commit-msg, pre-commit, pre-push]

repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: "v2.7.2"
    hooks:
      - id: conventional-commits
        args: ["-c", ".git-commits.yaml"]
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        stages: ["pre-commit"]
      - id: check-merge-conflict
        stages: ["pre-commit"]
      - id: check-added-large-files
        stages: ["pre-commit"]
      - id: check-ast
        stages: ["pre-commit"]
      - id: check-executables-have-shebangs
        stages: ["pre-commit"]
      - id: check-symlinks
        stages: ["pre-commit"]
      - id: check-toml
        stages: ["pre-commit"]
      - id: check-yaml
        stages: ["pre-commit"]
      - id: debug-statements
        stages: ["pre-commit"]
      - id: end-of-file-fixer
        stages: ["pre-commit"]
      - id: trailing-whitespace
        stages: ["pre-commit"]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        stages: ["pre-commit"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock
        args: ["--check"]
        stages: ["pre-commit"]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check muffin
        language: system
        pass_filenames: false
        files: \.py$
        stages: ["pre-commit"]

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        files: \.py$
        stages: ["pre-push"]

      - id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        files: \.py$
        stages: ["pre-push"]
